"""Codex external agent — writes ``~/.codex/config.toml`` + ``AGENTS.md``.

The ``config.toml`` portion is one-shot: we write it once during
bootstrap with an MCP token environment-variable reference and the workspace path, then
never touch it again. Users routinely edit Codex config to swap
models, tweak sandbox modes, add other MCP servers — clobbering those
edits every sync run would be hostile.

The ``AGENTS.md`` portion *is* kept fresh by the periodic sync
service, because it's pure derived data (Nerve workspace files →
bundle string).
"""

from __future__ import annotations

import os
from pathlib import Path

from nerve.external_agents.registry import (
    AgentSetupResult,
    ExternalAgent,
    FileTarget,
)
from nerve.external_agents.renderers.codex_global import CodexGlobalRenderer
from nerve.external_agents.writer import ConfigWriter


# Pinned for predictable diffs in tests. We could template via Jinja
# but Codex's config schema is tiny and string-formatting is more
# transparent for review.
CONFIG_TOML_TEMPLATE = '''\
# Generated by Nerve — see https://github.com/ClickHouse/nerve
#
# This file is written ONCE at bootstrap. The sync service does NOT
# rewrite it on subsequent runs, so edits to model preferences,
# sandbox mode, etc. are safe to make here. The memory bundle in
# ~/.codex/AGENTS.md *is* kept fresh and will be rewritten.

approval_policy = "{approval_policy}"
sandbox_mode = "{sandbox_mode}"

[projects."{workspace}"]
trust_level = "trusted"

# Nerve MCP server — exposes the full Nerve tool registry (tasks,
# memory, plans, skills, notifications, ...) to Codex. Authentication
# uses a gateway JWT supplied at process launch. Never persist bearer
# credentials in this generated TOML file.
[mcp_servers.nerve]
url = "{nerve_url}"
bearer_token_env_var = "NERVE_MCP_TOKEN"
startup_timeout_sec = 30
tool_timeout_sec = 60
default_tools_approval_mode = "auto"
'''


class CodexAgent(ExternalAgent):
    """OpenAI Codex (``codex`` CLI)."""

    name = "codex"
    display_name = "Codex"
    cli_command = "codex"

    DEFAULT_APPROVAL_POLICY = "never"
    DEFAULT_SANDBOX_MODE = "danger-full-access"

    def default_config_paths(self) -> list[Path]:
        return [
            Path("~/.codex/config.toml").expanduser(),
            Path("~/.codex/AGENTS.md").expanduser(),
        ]

    def default_file_targets(self, workspace: Path) -> list[FileTarget]:
        return [
            FileTarget(
                output=Path("~/.codex/AGENTS.md").expanduser(),
                includes=[
                    "SOUL.md",
                    "IDENTITY.md",
                    "USER.md",
                    "TOOLS.md",
                    "MEMORY.md",
                ],
                style="codex-global",
            ),
            # Workspace AGENTS.md is left alone — it's the source of
            # truth for project-scoped conventions, not derived data.
        ]

    async def write_config(
        self,
        *,
        nerve_url: str,
        mcp_token: str,
        workspace: Path,
        writer: ConfigWriter,
    ) -> AgentSetupResult:
        config_path = Path("~/.codex/config.toml").expanduser()
        rendered = CONFIG_TOML_TEMPLATE.format(
            approval_policy=self.DEFAULT_APPROVAL_POLICY,
            sandbox_mode=self.DEFAULT_SANDBOX_MODE,
            workspace=str(workspace),
            nerve_url=nerve_url,
        )
        backups: list[Path] = []
        warnings: list[str] = []

        b = writer.write(config_path, rendered)
        if b is not None:
            backups.append(b)

        # Initial AGENTS.md render — sync service will keep it fresh
        agents_md_path = Path("~/.codex/AGENTS.md").expanduser()
        target = self.default_file_targets(workspace)[0]
        bundle = CodexGlobalRenderer().render(target, workspace=workspace)
        b = writer.write(agents_md_path, bundle)
        if b is not None:
            backups.append(b)

        if not self.smoke_check():
            warnings.append(
                "`codex` CLI not found on PATH — install with "
                "`npm i -g @openai/codex` to actually use this config."
            )
        if not os.environ.get("NERVE_MCP_TOKEN"):
            warnings.append(
                "Set NERVE_MCP_TOKEN in the environment that launches `codex`; "
                "the bearer token is intentionally not stored in config.toml."
            )

        return AgentSetupResult(
            agent=self.name,
            config_files_written=[config_path, agents_md_path],
            backups_created=backups,
            token=mcp_token,
            warnings=warnings,
        )
